### ISSUE TITLE
chore: checklist for basic usability

### ISSUE THREAD

**Issue by insertish** [revoltchat/frontend#154]
In order of difficulty (from easiest) / importance weighted together:
- [x] Show channel topic
- [x] Show DMs in server list (overflow if too many)
- [x] Render system messages
- [x] Fix font on categories to be more bold
- [x] feat: typing indicator
- [x] issue: reply pings do not include '@'
- [x] #128
- [x] #122 
- [x] #126 
- [x] Send message button
- [x] Member sidebar
- [x] Add buttons to toggle right sidebar
- [x] #144
- [x] #155
- [x] Show message as it is being sent

Then work on message renderer

![image](https://user-images.githubusercontent.com/38285861/227790479-609cac02-426d-4574-acb9-b479c5ed9e8e.png)

**Comment by insertish** [comment]
Closing in favour of individual issues
